/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aggregateSpecSusp;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ExtractALine extractALine = new ExtractALine(0);
    }
}
